import Link from 'next/link';

export default function AboutPage() {
  return (
    <div>
      <section className="bg-gradient-to-br from-navy-950 via-navy-900 to-navy-800 text-white py-12">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h1 className="text-3xl sm:text-4xl font-bold mb-2">About Vedic Astrology</h1>
          <p className="text-navy-300">
            Understanding the ancient science of Jyotish and how this site works
          </p>
        </div>
      </section>

      <section className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-8">
        {/* What is Vedic Astrology */}
        <div className="bg-white rounded-xl border border-navy-100 p-6">
          <h2 className="font-semibold text-xl mb-4 text-navy-900">
            What is Vedic Astrology?
          </h2>
          <div className="text-slate-600 space-y-3 text-sm leading-relaxed">
            <p>
              Vedic Astrology, known as <strong>Jyotish Shastra</strong> (the &ldquo;Science of
              Light&rdquo;), is an ancient Indian system of astronomy and astrology that dates
              back over 5,000 years. Unlike Western astrology which uses the tropical zodiac,
              Vedic astrology uses the <strong>sidereal zodiac</strong>, which accounts for the
              precession of equinoxes.
            </p>
            <p>
              The key difference is that the sidereal zodiac is aligned with the actual
              positions of the constellations in the sky, while the tropical zodiac is
              aligned with the seasons. This means your Vedic (sidereal) sign may differ
              from your Western (tropical) sign by approximately 23-24 degrees.
            </p>
            <p>
              In Vedic astrology, the <strong>Moon sign (Rashi)</strong> is considered the
              most important indicator of personality, mind, and daily life experiences,
              whereas Western astrology emphasizes the Sun sign.
            </p>
          </div>
        </div>

        {/* How This Site Works */}
        <div className="bg-white rounded-xl border border-navy-100 p-6">
          <h2 className="font-semibold text-xl mb-4 text-navy-900">
            How This Site Works
          </h2>
          <div className="text-slate-600 space-y-3 text-sm leading-relaxed">
            <p>
              This website calculates <strong>real planetary positions</strong> using
              astronomical ephemeris data. All calculations are performed in your browser
              using accurate astronomical algorithms.
            </p>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>
                <strong>Sidereal Zodiac</strong>: We use the Lahiri ayanamsa (the official
                ayanamsa of the Indian Government) to convert tropical positions to sidereal.
              </li>
              <li>
                <strong>Navagraha</strong>: We calculate positions for all nine Vedic planets
                &mdash; Sun (Surya), Moon (Chandra), Mars (Mangal), Mercury (Budha), Jupiter
                (Guru), Venus (Shukra), Saturn (Shani), Rahu, and Ketu.
              </li>
              <li>
                <strong>Transit Analysis (Gochar)</strong>: Daily insights are generated by
                analyzing the current planetary transits relative to your Moon sign, following
                traditional Vedic transit rules.
              </li>
              <li>
                <strong>Moon Phases</strong>: Accurate lunar phase calculations for any date,
                including new moons, full moons, and all intermediate phases.
              </li>
              <li>
                <strong>Retrogrades &amp; Eclipses</strong>: Real-time detection of planetary
                retrogrades and upcoming solar and lunar eclipses.
              </li>
            </ul>
          </div>
        </div>

        {/* The 12 Moon Signs */}
        <div className="bg-white rounded-xl border border-navy-100 p-6">
          <h2 className="font-semibold text-xl mb-4 text-navy-900">
            The 12 Rashis (Moon Signs)
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {[
              { name: 'Mesha (Aries)', ruler: 'Mars', element: 'Fire', desc: 'Pioneering, energetic, independent' },
              { name: 'Vrishabha (Taurus)', ruler: 'Venus', element: 'Earth', desc: 'Stable, sensual, determined' },
              { name: 'Mithuna (Gemini)', ruler: 'Mercury', element: 'Air', desc: 'Communicative, versatile, intellectual' },
              { name: 'Karka (Cancer)', ruler: 'Moon', element: 'Water', desc: 'Nurturing, intuitive, emotional' },
              { name: 'Simha (Leo)', ruler: 'Sun', element: 'Fire', desc: 'Royal, confident, creative' },
              { name: 'Kanya (Virgo)', ruler: 'Mercury', element: 'Earth', desc: 'Analytical, practical, meticulous' },
              { name: 'Tula (Libra)', ruler: 'Venus', element: 'Air', desc: 'Balanced, diplomatic, aesthetic' },
              { name: 'Vrishchika (Scorpio)', ruler: 'Mars', element: 'Water', desc: 'Intense, transformative, perceptive' },
              { name: 'Dhanu (Sagittarius)', ruler: 'Jupiter', element: 'Fire', desc: 'Philosophical, adventurous, optimistic' },
              { name: 'Makara (Capricorn)', ruler: 'Saturn', element: 'Earth', desc: 'Ambitious, disciplined, structured' },
              { name: 'Kumbha (Aquarius)', ruler: 'Saturn', element: 'Air', desc: 'Humanitarian, innovative, progressive' },
              { name: 'Meena (Pisces)', ruler: 'Jupiter', element: 'Water', desc: 'Spiritual, compassionate, imaginative' },
            ].map((sign) => (
              <div key={sign.name} className="p-3 rounded-lg bg-navy-50 border border-navy-100">
                <h3 className="font-medium text-navy-800 text-sm">{sign.name}</h3>
                <p className="text-xs text-slate-500 mt-0.5">
                  Ruler: {sign.ruler} &middot; {sign.element} &middot; {sign.desc}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Understanding Transit Analysis */}
        <div className="bg-white rounded-xl border border-navy-100 p-6">
          <h2 className="font-semibold text-xl mb-4 text-navy-900">
            Understanding Transit Analysis (Gochar)
          </h2>
          <div className="text-slate-600 space-y-3 text-sm leading-relaxed">
            <p>
              In Vedic astrology, <strong>Gochar</strong> (transit analysis) examines how
              the current positions of planets affect different areas of your life based on
              your Moon sign. Each planet transiting through different houses from your Moon
              sign activates specific life themes.
            </p>
            <p>
              Our daily insights analyze six key life areas based on planetary transits:
            </p>
            <ul className="list-disc list-inside space-y-1 ml-2">
              <li><strong>Career &amp; Profession</strong> &mdash; 10th house focus</li>
              <li><strong>Relationships &amp; Love</strong> &mdash; 7th house focus</li>
              <li><strong>Health &amp; Wellness</strong> &mdash; 6th house focus</li>
              <li><strong>Finances &amp; Wealth</strong> &mdash; 2nd and 11th house focus</li>
              <li><strong>Spirituality &amp; Growth</strong> &mdash; 9th and 12th house focus</li>
              <li><strong>General Outlook</strong> &mdash; Overall planetary energy</li>
            </ul>
          </div>
        </div>

        {/* Disclaimer */}
        <div className="bg-navy-50 rounded-xl border border-navy-200 p-6">
          <h2 className="font-semibold text-lg mb-2 text-navy-800">Disclaimer</h2>
          <p className="text-slate-600 text-sm leading-relaxed">
            The content on this website is purely informational, generated from real
            astronomical transit data and traditional Vedic astrological frameworks. It is
            not intended as advice, predictions, or a substitute for professional consultation
            in any area of life. The insights describe planetary positions and their
            traditional associations &mdash; not fixed outcomes. Individual experiences
            vary based on the complete birth chart (Kundali) and many other factors.
            For accurate and personalised readings, please consult a professional astrologer.
          </p>
        </div>

        <div className="text-center">
          <Link
            href="/"
            className="inline-block bg-navy-600 text-white px-6 py-3 rounded-lg font-medium hover:bg-navy-700 transition-colors"
          >
            Explore Your Moon Sign &rarr;
          </Link>
        </div>
      </section>
    </div>
  );
}
